"""
Google Semiclassical Phase Estimation Strategy
===============================================

Implements qubit-recycled (semiclassical) phase estimation for Shor's
ECDLP algorithm, replacing the two multi-qubit counting registers and
bulk inverse QFT with two single recycled qubits and classically-
conditioned phase corrections.

Technique from Griffiths & Niu (1996), highlighted in Babbush et al.
(2026) "Securing Elliptic Curve Cryptocurrencies against Quantum
Vulnerabilities".

Qubit savings vs standard approach:
  - 4-bit curve:  16 -> 9 qubits
  - 10-bit curve: 40 -> 22 qubits
  - 13-bit curve: 52 -> 28 qubits (+ ancillas)
"""

from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
import numpy as np
import math
from typing import Tuple, Optional, List, Dict

from projecteleven import (
    CurveParams, EllipticCurve, PointEncoder,
    QuantumPointAdder, ShorECDLP,
)
from quantum_arithmetic import EfficientPermutationAdder


class SemiclassicalShorECDLP:
    """Shor's ECDLP with qubit-recycled phase estimation.

    Uses a single qubit per counting register, measured and reset
    sequentially with classically-conditioned phase corrections
    replacing the inverse QFT.
    """

    def __init__(self, params: CurveParams,
                 G: Tuple[int, int], Q: Tuple[int, int]):
        self.params = params
        self.G = G
        self.Q = Q
        self.n = params.n

        self.ec = EllipticCurve(params)
        self.encoder = PointEncoder(self.ec, G)

        n_bits = self.encoder.n_bits

        # Choose adder: dense unitary for small curves, permutation for larger
        if n_bits <= 6:
            self.adder = QuantumPointAdder(self.encoder)
            self._use_ancilla = False
        else:
            self.adder = EfficientPermutationAdder(self.encoder)
            self._use_ancilla = True

        # Delegate extraction to ShorECDLP (same bitstring format)
        self._extraction_solver = ShorECDLP(params, G, Q)

        if Q is not None and Q not in self.encoder.point_to_index:
            raise ValueError("Q is not in the group generated by G")

    def extract_discrete_log(self, counts: Dict[str, int]) -> Optional[int]:
        return self._extraction_solver.extract_discrete_log(counts)

    def build_circuit(self, num_counting: int = None,
                      max_corrections: int = 1) -> QuantumCircuit:
        """Build semiclassical Shor ECDLP circuit.

        Args:
            num_counting: Number of counting bits per register (default: n_bits+1).
            max_corrections: Maximum phase corrections per measurement step
                (approximate QFT truncation). Limits dynamic circuit overhead
                on IBM hardware. Use None for full corrections. Default 2
                retains the two dominant angles (-pi/2, -pi/4) per step.
        """
        n_bits = self.encoder.n_bits

        if num_counting is None:
            num_counting = n_bits + 1

        # Registers: 2 recycled qubits + point register (+ ancillas)
        j_qubit = QuantumRegister(1, 'j')
        k_qubit = QuantumRegister(1, 'k')
        pt_reg = QuantumRegister(n_bits, 'pt')

        num_ancilla = max(0, n_bits - 2) if self._use_ancilla else 0
        anc_reg = QuantumRegister(num_ancilla, 'anc') if num_ancilla > 0 else None

        # Classical register: same layout as standard solver
        # MSB-left: k_bits | j_bits | pt_bits
        total_clbits = 2 * num_counting + n_bits
        cr = ClassicalRegister(total_clbits, 'cr')

        regs = [j_qubit, k_qubit, pt_reg]
        if anc_reg:
            regs.append(anc_reg)
        regs.append(cr)

        qc = QuantumCircuit(*regs, name=f"Shor_ECDLP_semiclassical_n{self.n}")

        ancilla_qubits = list(anc_reg) if anc_reg else None

        # --- Phase 1: j-register (controlled additions of 2^i * G) ---
        self._semiclassical_register(
            qc, j_qubit[0], pt_reg, ancilla_qubits, cr,
            num_counting, n_bits, self.G, cl_offset=n_bits,
            max_corrections=max_corrections,
        )

        # --- Phase 2: k-register (controlled additions of 2^i * Q) ---
        self._semiclassical_register(
            qc, k_qubit[0], pt_reg, ancilla_qubits, cr,
            num_counting, n_bits, self.Q, cl_offset=n_bits + num_counting,
            max_corrections=max_corrections,
        )

        # Measure point register (bits 0..n_bits-1 of cr)
        for i in range(n_bits):
            qc.measure(pt_reg[i], cr[i])

        return qc

    def _semiclassical_register(self, qc, recycled_qubit, pt_reg,
                                 ancilla_qubits, cr, num_counting, n_bits,
                                 base_point, cl_offset, max_corrections=2):
        """Build one semiclassical counting register using qubit recycling.

        Measures MSB first (idx=0 is MSB), stores each bit at the
        classical register position matching the standard solver layout.

        Uses approximate QFT truncation: only the nearest max_corrections
        previously measured bits contribute phase corrections. Corrections
        from farther bits have angles < pi/2^max_corrections which are
        below the hardware noise floor.
        """
        # Precompute point powers: 2^bit_index * base_point
        powers = {}
        P = base_point
        for bit_index in range(num_counting):
            powers[bit_index] = P
            if P is not None:
                P = self.ec.add(P, P)
                if P is None and base_point is not None:
                    P = base_point

        for idx in range(num_counting):
            bit_index = num_counting - 1 - idx  # MSB-first: first iteration = MSB
            power_point = powers[bit_index]

            # Reset and prepare
            qc.reset(recycled_qubit)
            qc.h(recycled_qubit)

            # Controlled addition of 2^bit_index * base_point
            if power_point is not None:
                if self._use_ancilla:
                    self.adder.apply_controlled_add(
                        qc, recycled_qubit, list(pt_reg),
                        power_point, ancilla_qubits
                    )
                else:
                    self.adder.apply_controlled_add(
                        qc, recycled_qubit, list(pt_reg), power_point
                    )

            # Phase corrections from nearest previously measured bits only
            # (approximate QFT truncation to reduce dynamic circuit overhead)
            correction_start = max(0, idx - max_corrections) if max_corrections is not None else 0
            for prev_idx in range(correction_start, idx):
                prev_bit_index = num_counting - 1 - prev_idx
                angle = -np.pi / (2 ** (prev_bit_index - bit_index))
                prev_clbit = cr[cl_offset + prev_bit_index]
                with qc.if_test((prev_clbit, 1)):
                    qc.p(angle, recycled_qubit)

            # Final Hadamard and measurement
            qc.h(recycled_qubit)
            qc.measure(recycled_qubit, cr[cl_offset + bit_index])

    def qubit_count(self) -> Dict[str, int]:
        n_bits = self.encoder.n_bits
        num_counting = n_bits + 1
        num_ancilla = max(0, n_bits - 2) if self._use_ancilla else 0
        return {
            "j_register": 1,
            "k_register": 1,
            "point_register": n_bits,
            "ancilla": num_ancilla,
            "total": 2 + n_bits + num_ancilla,
            "group_order": self.n,
            "standard_total": 2 * num_counting + n_bits + num_ancilla,
            "qubit_savings": 2 * (num_counting - 1),
        }
